#index:
#    path: /
#    controller: App\Controller\DefaultController::index
nelmio_api_doc:
    path: /api/v1/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
